import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Marque from "@/components/Marque";
import Footer from "@/components/Footer";

const notoSerifBangla = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "News 24 BD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBangla.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <Marque />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
